
services:
  app:
    build:
      context: ./backend12
      dockerfile:  Dockerfile
    image: jasperphp-app
    restart: unless-stopped
    volumes:
      - ./backend12:/var/www/html/backend
    command: sh -c "chown -R www-data:www-data /var/www/html/backend/storage /var/www/html/backend/vendor /var/www/html/backend/bootstrap/cache /var/www/html/backend/database && php artisan route:clear && php artisan config:clear && php-fpm"
    ports:
      - "9000:9000"
    networks:
      - jasperphp-network

  nginx:
    image: nginx:alpine
    restart: unless-stopped

    volumes:
      - ./backend12:/var/www/html/backend
      - ./frontend/package/dist:/var/www/html/frontend
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - jasperphp-network

networks:
  jasperphp-network:
    driver: bridge

