services:
  app:
    build:
      context: ./backend12
      dockerfile: Dockerfile
    image: jasperphp-app
    restart: unless-stopped
    volumes:
      - ./backend12:/var/www/html/backend
      - /var/www/html/backend/node_modules
    environment:
      - NODE_PATH=/usr/lib/node_modules:/usr/local/lib/node_modules
    command: sh -c "chown -R www-data:www-data /var/www/html/backend/storage /var/www/html/backend/bootstrap/cache /var/www/html/backend/database && php artisan route:clear && php artisan config:clear && php artisan octane:start --server=swoole --host=0.0.0.0 --port=8000 --watch"
    ports:
      - "8000:8000"
    networks:
      - jasperphp-network

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./backend12:/var/www/html/backend
      - ./frontend/package/dist:/var/www/html/frontend
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "89:80"
    networks:
      - jasperphp-network

networks:
  jasperphp-network:
    driver: bridge

volumes:
  vendor:
